Подключение Vuex. Работа с глобальным состоянием приложения
htmlacademy-vue/1986427-pizza-1 pull request #4
Opened 2022-07-18 18:18 UTC by EvgNikitin

---
:mortar_board: [Подключение Vuex. Работа с глобальным состоянием приложения](https://up.htmlacademy.ru/vue/1/user/1986427/tasks/5)

2022-07-18 21:40 UTC, enotke requested changes

2022-07-19 07:27 UTC, EvgNikitin commented on src/frontend/src/modules/cart/components/CartProductList.vue
> +          :disabled="isDisabled(order.id, userOrder)"
@enotke здесь вообще не задавать ограничения или поставить, скажем 10 шт.?

2022-07-19 07:28 UTC, EvgNikitin commented on src/frontend/src/modules/cart/components/CartAdditional.vue
> +            :disabled="isDisabled(item.id, getAdditionalGoods)"
@enotke здесь так же вообще не задавать ограничения или поставить, скажем 10 шт.?

2022-07-19 07:36 UTC, enotke commented on src/frontend/src/modules/cart/components/CartAdditional.vue
> +            :disabled="isDisabled(item.id, getAdditionalGoods)"
По ТЗ ограничений нет

2022-07-19 07:37 UTC, enotke commented on src/frontend/src/modules/cart/components/CartProductList.vue
> +          :disabled="isDisabled(order.id, userOrder)"
По ТЗ ограничений нет

2022-07-19 18:53 UTC, merged